name:                corenlp-parser
version:             0.4.0.0
synopsis:            Launches CoreNLP and parses the JSON output
description:         Launches CoreNLP and parses the JSON output
homepage:            https://github.com/k-bx/corenlp-parser#readme
license:             BSD3
author:              Kostiantyn Rybnikov
maintainer:          k-bx@k-bx.com
copyright:           All Rights Reserved
category:            Natural Language Processing
extra-source-files:
- README.md
extra-libraries: rocksdb

dependencies:
  - aeson
  - async
  - base >= 4.7 && < 5
  - cryptonite
  - data-default
  - directory
  - process
  - raw-strings-qq
  - rocksdb-haskell
  - safe-exceptions
  - split
  - string-class
  - store
  - temporary
  - text
  - unordered-containers

library:
  source-dirs:      src
  ghc-options: -Wall
